language: node_js
node_js:
  - "7"
  - "8"

before_install:
  - npm install karma-coveralls
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:node
  - ./node_modules/.bin/karma start --single-run --browsers Firefox,Chrome_travis --reporters mocha,coverage,coveralls .config/karma.conf.js
